Update r-daily.yml

diff --git a/.github/workflows/r-daily.yml b/.github/workflows/r-daily.yml
--- a/.github/workflows/r-daily.yml
+++ b/.github/workflows/r-daily.yml
@@ -30,6 +30,18 @@ jobs:
           git checkout r-daily-source
           git fetch upstream
           git reset --hard upstream/master
+
+      - name: Cherry-pick R bump
+        run: |
+          set -e
+          git fetch upstream
+          if git cherry-pick -m 1 a65b87c485e1^..ad0a16337834; then
+            echo "Cherry-pick successful"
+          else
+            echo "Cherry-pick failed — aborting"
+            git cherry-pick --abort
+            exit 1
+          fi
           
       - name: Cherry-pick phart PR
         run: |
@@ -93,18 +105,6 @@ jobs:
      #   run: |
      #     sed -i 's|hash = "sha256-tCp5IUADhmRbEBBbkcaHKHh9tcTIPJ9sMKzc5jLhu3A=";|hash = "sha256-DXH/cQbsac18Z+HpXtGjzuNViAkx8ut4xTABSp43nyA=";|' pkgs/applications/science/math/R/default.nix
      #     sed -i 's|version = "4.5.1";|version = "4.5.2";|' pkgs/applications/science/math/R/default.nix
-
-      - name: Cherry-pick R bump
-        run: |
-          set -e
-          git fetch upstream
-          if git cherry-pick -m 1 a65b87c485e1227152f23b979d499e1b553b4655^..ad0a16337834148ab52fff49e2901745d3e9c12a; then
-            echo "Cherry-pick successful"
-          else
-            echo "Cherry-pick failed — aborting"
-            git cherry-pick --abort
-          exit 1
-          fi
 
       - name: Install Nix
         uses: DeterminateSystems/nix-installer-action@main
